# numpy

In [2]:
import numpy as np

In [74]:
a = np.arange(15)
b = a.reshape(3,5)
c = np.array([
    [
        [1,2],
        [11,21]
    ],
    [
        [3,4],
        [31,32]
    ],
    [
        [5,6],
        [51,52]
    ]
])
d =np.array([[[]]])

In [75]:
print(f"a:\n{a}")
print(f"b:\n{b}")
print(f"c:\n{c}")
print(f"d:\n{d}")

a:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
b:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
c:
[[[ 1  2]
  [11 21]]

 [[ 3  4]
  [31 32]]

 [[ 5  6]
  [51 52]]]
d:
[]


## ndarrya.ndim 维度(轴)数量

In [76]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

1
2
3
3


## ndarray.shape:返回每个维度(轴)的元素数量信息

In [81]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(15,)
(3, 5)
(3, 2, 2)
(1, 1, 0)


## ndarrya.size:元素总数量

In [82]:
print(a.size)
print(b.size)
print(c.size)
print(d.size)

15
15
12
0


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.